/** §24 / §13.29 engine summaries, shared by the methodology pages and the
 * markdown representations served to agents. Descriptive only — every
 * statutory value referenced lives in rule packs, not here. */
export const ENGINE_NOTES: Record<string, { name: string; method: string; formulas: string[] }> = {
  E01: { name: "Core money and period engine", method: "Integer-cent money arithmetic and explicit period conversions (52 weeks, 26 fortnights, 12 months per year).", formulas: [] },
  E02: { name: "Australian annual tax engine", method: "Piecewise progressive brackets (§13.13), LITO taper, Medicare levy with low-income phase-in, Medicare levy surcharge tiers and study-loan repayment (marginal from 2025-26, whole-income before), all from versioned rule packs.", formulas: ["F-TAX-001 progressive brackets", "F-TAX-002 LITO", "F-TAX-003 Medicare levy", "F-TAX-004 MLS", "F-TAX-005 STSL"] },
  E03: { name: "PAYG withholding engine", method: "The ATO statement-of-formulas method: y = a·x − b on weekly-equivalent earnings with schedule rounding, plus the Schedule 8 study-loan component. Never annual tax divided by pay periods (§13.16).", formulas: ["F-PAYG-001 schedule formulas"] },
  E04: { name: "Compensation engine", method: "Package decomposition base = package ÷ (1 + r), capped by the maximum contribution base, with an iterative §12.1.7 verification path.", formulas: ["F-PAY-001 package decomposition"] },
  E07: { name: "Scheduled mortgage ledger", method: "A payment-period ledger with dated events (rates, extras, offsets, fees), §13.9 offset treatment and §12.5.8 reconciliation invariants on every period. Daily accrual is not modelled at P0.", formulas: ["§13.7 recurrence", "§13.9 offset"] },
  E08: { name: "Property transaction engine", method: "General transfer duty as bracket base plus rate per $100 or part thereof, from per-state rule packs. Unsupported states block rather than guess.", formulas: ["§12.8 duty brackets"] },
  E10: { name: "Affordability estimate (lite)", method: "Monthly surplus after an editable expense floor, converted to an indicative range via the §13.5 payment formula at your rate plus an editable buffer. A range, never an approval.", formulas: ["§13.5 payment"] },
  E11: { name: "Amortising loan engine", method: "Closed-form §13.5 payment (with §13.6 balloon), then a full §13.7 schedule with per-period cent rounding and a capped final-payment adjustment.", formulas: ["§13.5 payment", "§13.6 balloon", "§13.7 recurrence"] },
  E12: { name: "Revolving credit engine", method: "Monthly statement cycles: interest on the opening balance, configurable minimum rule (percent with floor), fixed-payment strategy, promotional expiry on its exact date.", formulas: ["§12.11 cycles"] },
  E14: { name: "Savings engine", method: "§13.11 future value with contributions, cross-checked by period simulation; goal solving by closed-form inversion verified through the forward calculation.", formulas: ["§13.11 future value"] },
  E19: { name: "Contractor economics engine", method: "Billable capacity from weekdays minus leave, holidays and non-billable days times utilisation; day rate covers income, super replacement, overheads and the chosen margin. GST is quoted on top and never treated as revenue.", formulas: ["§12.16 capacity"] },
  E20: { name: "Business arithmetic engine", method: "GST arithmetic per §13.18 with explicit rounding levels and largest-remainder allocation so invoice lines always reconcile to totals.", formulas: ["F-GST-001", "F-GST-002"] },
  E24: { name: "Financial solver", method: "Monotonic bisection with §13.28 safeguards: bounds, tolerances, iteration caps, discontinuity detection and unattainable-target reporting.", formulas: ["§13.28 bisection"] },
};
